language: rust

rust:
  - nightly

os:
  - linux

addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

script:
  - cargo build --verbose
  - cargo update
  - RUST_BACKTRACE=full cargo test --verbose
