[package]
name = "semverver"
description = "Automatic verification of SemVer adhrence in rust library crates"
repository = "https://github.com/ibabushkin/rust-semverver"
version = "0.1.0"
authors = ["Inokentiy Babushkin <twk@twki.de>"]
license = "BSD3"

[[bin]]
name = "cargo-semver"
path = "src/bin/cargo_semver.rs"

[[bin]]
name = "rust-semverver"
path = "src/bin/rust_semverver.rs"

[dependencies]
cargo = "0.24"
crates-io = "0.13"
env_logger = "0.5"
log = "0.4"
semver = "0.9"

[dev-dependencies]
quickcheck = "0.6"
