[package]
name = "semverver"
description = "Automatic verification of SemVer adhrence in rust library crates"
repository = "https://github.com/ibabushkin/rust-semverver"
version = "0.1.0"
authors = ["Inokentiy Babushkin <twk@twki.de>"]
license = "BSD3"

[[bin]]
name = "cargo-semver"
path = "src/bin/cargo_semver.rs"

[[bin]]
name = "rust-semverver"
path = "src/bin/rust_semverver.rs"

[dependencies]
cargo = "^0.18.0"
crates-io = "^0.7.0"
env_logger = "^0.4.0"
log = "^0.3.0"
semver = "^0.7.0"

[dev-dependencies]
quickcheck = "^0.4.1"
